/**
 * Render an EntityReport as a TypeScript module: one `interface` per table,
 * with `@chrysalis-provenance` JSDoc tags citing the schema location + sample
 * trace IDs. These tags are the *structural* link between emitted code and
 * the evidence that justified each field.
 */

import type { EntityReport, EntityFieldReport, SchemaReport } from "./merge.js";

export interface EmitTypesOptions {
  readonly bannerComment?: string; // prepended as a file-level comment
  readonly exportPrefix?: string; // default "" (e.g. "Domain")
}

export function emitTypes(report: SchemaReport, opts: EmitTypesOptions = {}): string {
  const banner =
    opts.bannerComment ??
    `Generated by @chrysalis/archaeology. Do not edit by hand.
 Regenerate with: chrysalis archaeology <schema.sql> [--traces <dir>] --out <path>`;
  const lines: string[] = [];
  lines.push(`/**`);
  for (const l of banner.split("\n")) lines.push(` * ${l}`);
  lines.push(` */`);
  lines.push("");
  lines.push(`// eslint-disable @typescript-eslint/no-namespace`);
  lines.push("");

  for (const entity of report.entities) {
    lines.push(...renderEntity(entity, opts.exportPrefix ?? ""));
    lines.push("");
  }

  if (report.orphanShapes.length > 0) {
    lines.push("/**");
    lines.push(" * Observed-but-unattributed row shapes. These came from SQL we could");
    lines.push(" * not tie to a specific table (subqueries, function calls, views).");
    lines.push(" * Surfaced here so they don't disappear silently.");
    lines.push(" */");
    for (const s of report.orphanShapes) {
      lines.push(` // orphan: [${s.fields.join(", ")}] (${s.statementCount} statement(s))`);
    }
    lines.push("");
  }

  if (report.unknownDdl.length > 0) {
    lines.push("/**");
    lines.push(" * DDL fragments the schema parser could not interpret. Upgrade the");
    lines.push(" * parser in packages/archaeology/src/parse-schema.ts if these matter.");
    lines.push(" */");
    for (const u of report.unknownDdl) {
      lines.push(` // unknown(${u.table} @ ${u.source.file}:${u.source.line}): ${u.raw.replace(/\s+/g, " ")}`);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}

function renderEntity(entity: EntityReport, prefix: string): string[] {
  const out: string[] = [];
  const iface = `${prefix}${entity.typescriptName}`;
  out.push(`/**`);
  out.push(` * ${iface} — derived from table \`${entity.name}\``);
  out.push(` * @chrysalis-provenance schema ${entity.fromSchema.file}:${entity.fromSchema.line}`);
  out.push(` * @chrysalis-provenance observed-statements ${entity.observedStatementCount}`);
  out.push(` */`);
  out.push(`export interface ${iface} {`);
  for (const f of entity.fields) {
    out.push(...renderField(f));
  }
  out.push(`}`);
  return out;
}

function renderField(f: EntityFieldReport): string[] {
  const out: string[] = [];
  out.push(`  /**`);
  out.push(`   * ${describeKind(f)}`);
  for (const p of f.provenance) {
    out.push(`   * @chrysalis-provenance ${p.kind} — ${p.detail}`);
  }
  if (f.conflicts.length > 0) {
    for (const c of f.conflicts) out.push(`   * @chrysalis-conflict ${c}`);
  }
  out.push(`   */`);
  const nameToken = /^[A-Za-z_][A-Za-z0-9_]*$/.test(f.name) ? f.name : JSON.stringify(f.name);
  out.push(`  ${nameToken}${f.nullable ? "?" : ""}: ${f.typescriptType};`);
  return out;
}

function describeKind(f: EntityFieldReport): string {
  switch (f.kind) {
    case "ddl":
      return "Declared in DDL; no observations yet. Treat as ground truth until proven otherwise.";
    case "observed-only":
      return "Observed in traces but not declared in DDL. Treat as evidence-only.";
    case "ddl-and-observed":
      return "Declared in DDL and confirmed by observations.";
  }
}
