/**
 * Render a SchemaReport as Drizzle sqlite-core table definitions. Column layout
 * and nullability follow the merged archaeology entity fields (same contract as
 * `emitTypes` / `domain.ts`).
 */

import type { ColumnSchema } from "./parse-schema.js";
import type { EntityFieldReport, EntityReport, SchemaReport } from "./merge.js";

export interface EmitDrizzleSchemaOptions {
  readonly bannerComment?: string;
}

function colNameLit(name: string): string {
  return JSON.stringify(name);
}

function drizzleBuilderForDdl(ddl: ColumnSchema): string {
  const cn = colNameLit(ddl.name);
  const t = ddl.type;
  let core: string;
  switch (t.kind) {
    case "int":
      if (ddl.primaryKey && ddl.autoIncrement) {
        core = `integer(${cn}).primaryKey({ autoIncrement: true })`;
      } else if (ddl.primaryKey) {
        core = `integer(${cn}).primaryKey()`;
      } else {
        core = `integer(${cn})`;
      }
      break;
    case "float":
      core = `real(${cn})`;
      break;
    case "bool":
      core = `integer(${cn}, { mode: "boolean" })`;
      break;
    case "string":
    case "timestamp":
    case "date":
    case "enum":
      core = `text(${cn})`;
      break;
    case "blob":
      core = `blob(${cn})`;
      break;
    case "unknown":
      core = `text(${cn})`;
      break;
  }
  return core;
}

function renderField(f: EntityFieldReport): string {
  const key = f.name;
  let rhs: string;
  if (f.ddl) {
    rhs = drizzleBuilderForDdl(f.ddl);
  } else {
    rhs = `text(${colNameLit(f.name)})`;
  }
  if (f.ddl?.unique && !f.ddl.primaryKey) {
    rhs += ".unique()";
  }
  if (!f.nullable && !(f.ddl?.primaryKey && f.ddl.type.kind === "int")) {
    rhs += ".notNull()";
  }
  return `  ${key}: ${rhs},`;
}

function collectImports(report: SchemaReport): string[] {
  const names = new Set<string>(["sqliteTable"]);
  for (const e of report.entities) {
    for (const f of e.fields) {
      if (!f.ddl) {
        names.add("text");
        continue;
      }
      switch (f.ddl.type.kind) {
        case "int":
        case "bool":
          names.add("integer");
          break;
        case "float":
          names.add("real");
          break;
        case "blob":
          names.add("blob");
          break;
        case "string":
        case "timestamp":
        case "date":
        case "enum":
        case "unknown":
          names.add("text");
          break;
      }
    }
  }
  return [...names].sort();
}

function renderEntity(e: EntityReport): string[] {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Table \`${e.name}\` — ${e.typescriptName}`);
  lines.push(` * @chrysalis-provenance schema ${e.fromSchema.file}:${e.fromSchema.line}`);
  lines.push(` */`);
  lines.push(`export const ${e.name} = sqliteTable(${JSON.stringify(e.name)}, {`);
  for (const f of e.fields) {
    lines.push(renderField(f));
  }
  lines.push(`});`);
  return lines;
}

export function emitDrizzleSchema(report: SchemaReport, opts: EmitDrizzleSchemaOptions = {}): string {
  const banner =
    opts.bannerComment ??
    `Generated by @chrysalis/archaeology. Do not edit by hand.
Regenerate with: chrysalis archaeology <schema.sql> [--traces <dir>] --out <path>`;
  const lines: string[] = [];
  lines.push(`/**`);
  for (const l of banner.split("\n")) lines.push(` * ${l}`);
  lines.push(` */`);
  lines.push("");
  const im = collectImports(report).join(", ");
  lines.push(`import { ${im} } from "drizzle-orm/sqlite-core";`);
  lines.push("");
  for (const entity of report.entities) {
    lines.push(...renderEntity(entity));
    lines.push("");
  }
  return lines.join("\n").trimEnd() + "\n";
}
