/** Auto deepen batch n11a — generated by wisp-fidelity-deepen-auto (D6445). */
export const BATCH_ID = "n11a";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11a";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust GET round n11a (D6445)";
export const AUTO = true;
export const PASSES = [
  { id: 263, title: "Auto GET /api/bundles/" },
  { id: 264, title: "Auto GET /api/customer-billing/" },
  { id: 265, title: "Auto GET /api/customer-portal/auth/me" },
  { id: 266, title: "Auto GET /api/customer-portal/billing" },
  { id: 267, title: "Auto GET /api/customer-portal/billing/settings" },
  { id: 268, title: "Auto GET /api/customer-portal/service" },
  { id: 269, title: "Auto GET /api/customer-portal/tickets" },
  { id: 270, title: "Auto GET /api/customers/" },
  { id: 271, title: "Auto GET /api/device-assignment/unassigned" },
  { id: 272, title: "Auto GET /api/epc/checkin/monitoring-devices" },
];
export const REFRESH_PATHS = ["/api/bundles","/api/customer-billing","/api/customer-portal","/api/customers","/api/device-assignment","/api/epc"];
export const TARGETS = [
  {
    "pass": 263,
    "path": "/api/bundles/",
    "source": "routes/hardwareBundles.js",
    "risks": []
  },
  {
    "pass": 264,
    "path": "/api/customer-billing/",
    "source": "routes/customer-billing.js",
    "risks": []
  },
  {
    "pass": 265,
    "path": "/api/customer-portal/auth/me",
    "source": "routes/customer-portal-api.js",
    "risks": []
  },
  {
    "pass": 266,
    "path": "/api/customer-portal/billing",
    "source": "routes/customer-portal-api.js",
    "risks": []
  },
  {
    "pass": 267,
    "path": "/api/customer-portal/billing/settings",
    "source": "routes/customer-portal-api.js",
    "risks": []
  },
  {
    "pass": 268,
    "path": "/api/customer-portal/service",
    "source": "routes/customer-portal-api.js",
    "risks": []
  },
  {
    "pass": 269,
    "path": "/api/customer-portal/tickets",
    "source": "routes/customer-portal-api.js",
    "risks": []
  },
  {
    "pass": 270,
    "path": "/api/customers/",
    "source": "routes/customers.js",
    "risks": []
  },
  {
    "pass": 271,
    "path": "/api/device-assignment/unassigned",
    "source": "routes/device-assignment.js",
    "risks": []
  },
  {
    "pass": 272,
    "path": "/api/epc/checkin/monitoring-devices",
    "source": "routes/epc-checkin.js",
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  }
];

export async function runProbes(ctx) {
  const { probeDemo } = ctx;
  /** @type {Array<Record<string, unknown>>} */
  const probes = [];
  for (const t of TARGETS) {
    probes.push({
      pass: t.pass,
      ...(await probeDemo("GET", t.path)),
      source: t.source || "auto-discover",
      risks: t.risks || [],
    });
  }
  return probes;
}
