/** Auto deepen batch n11b — generated by wisp-fidelity-deepen-auto (D6445). */
export const BATCH_ID = "n11b";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11b";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust GET round n11b (D6445)";
export const AUTO = true;
export const PASSES = [
  { id: 273, title: "Auto GET /api/epc/checkin/snmp-subnets" },
  { id: 274, title: "Auto GET /api/epc/status" },
  { id: 275, title: "Auto GET /api/equipment-pricing/" },
  { id: 276, title: "Auto GET /api/equipment-pricing/price" },
  { id: 277, title: "Auto GET /api/incidents/" },
  { id: 278, title: "Auto GET /api/installation-documentation/" },
  { id: 279, title: "Auto GET /api/internal/plans" },
  { id: 280, title: "Auto GET /api/internal/tenant-settings" },
  { id: 281, title: "Auto GET /api/inventory/" },
  { id: 282, title: "Auto GET /api/maintain/dashboard/activity" },
];
export const REFRESH_PATHS = ["/api/epc","/api/equipment-pricing","/api/incidents","/api/installation-documentation","/api/internal","/api/inventory","/api/maintain"];
export const TARGETS = [
  {
    "pass": 273,
    "path": "/api/epc/checkin/snmp-subnets",
    "source": "routes/epc-checkin.js",
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 274,
    "path": "/api/epc/status",
    "source": "routes/epc.js",
    "risks": []
  },
  {
    "pass": 275,
    "path": "/api/equipment-pricing/",
    "source": "routes/equipment-pricing.js",
    "risks": []
  },
  {
    "pass": 276,
    "path": "/api/equipment-pricing/price",
    "source": "routes/equipment-pricing.js",
    "risks": []
  },
  {
    "pass": 277,
    "path": "/api/incidents/",
    "source": "routes/incidents.js",
    "risks": []
  },
  {
    "pass": 278,
    "path": "/api/installation-documentation/",
    "source": "routes/installation-documentation.js",
    "risks": []
  },
  {
    "pass": 279,
    "path": "/api/internal/plans",
    "source": "routes/internal.js",
    "risks": []
  },
  {
    "pass": 280,
    "path": "/api/internal/tenant-settings",
    "source": "routes/internal.js",
    "risks": []
  },
  {
    "pass": 281,
    "path": "/api/inventory/",
    "source": "routes/inventory.js",
    "risks": []
  },
  {
    "pass": 282,
    "path": "/api/maintain/dashboard/activity",
    "source": "routes/maintain.js",
    "risks": []
  }
];

export async function runProbes(ctx) {
  const { probeDemo } = ctx;
  /** @type {Array<Record<string, unknown>>} */
  const probes = [];
  for (const t of TARGETS) {
    probes.push({
      pass: t.pass,
      ...(await probeDemo("GET", t.path)),
      source: t.source || "auto-discover",
      risks: t.risks || [],
    });
  }
  return probes;
}
