/** Auto deepen batch n11c — generated by wisp-fidelity-deepen-auto (D6445). */
export const BATCH_ID = "n11c";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11c";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust GET round n11c (D6445)";
export const AUTO = true;
export const PASSES = [
  { id: 283, title: "Auto GET /api/maintain/dashboard/stats" },
  { id: 284, title: "Auto GET /api/mikrotik/devices/credentials" },
  { id: 285, title: "Auto GET /api/mme/customer-count" },
  { id: 286, title: "Auto GET /api/mme/online-subscribers" },
  { id: 287, title: "Auto GET /api/monitoring/graphs/" },
  { id: 288, title: "Auto GET /api/monitoring/snmp/metrics/latest" },
  { id: 289, title: "Auto GET /api/network/cpe" },
  { id: 290, title: "Auto GET /api/network/equipment" },
  { id: 291, title: "Auto GET /api/network/sectors" },
  { id: 292, title: "Auto GET /api/network/sites" },
];
export const REFRESH_PATHS = ["/api/maintain","/api/mikrotik","/api/mme","/api/monitoring","/api/network"];
export const TARGETS = [
  {
    "pass": 283,
    "path": "/api/maintain/dashboard/stats",
    "source": "routes/maintain.js",
    "risks": []
  },
  {
    "pass": 284,
    "path": "/api/mikrotik/devices/credentials",
    "source": "routes/mikrotik.js",
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 285,
    "path": "/api/mme/customer-count",
    "source": "routes/mme-status.js",
    "risks": []
  },
  {
    "pass": 286,
    "path": "/api/mme/online-subscribers",
    "source": "routes/mme-status.js",
    "risks": []
  },
  {
    "pass": 287,
    "path": "/api/monitoring/graphs/",
    "source": "routes/monitoring-graphs.js",
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 288,
    "path": "/api/monitoring/snmp/metrics/latest",
    "source": "routes/monitoring.js",
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 289,
    "path": "/api/network/cpe",
    "source": "routes/network.js",
    "risks": []
  },
  {
    "pass": 290,
    "path": "/api/network/equipment",
    "source": "routes/network.js",
    "risks": []
  },
  {
    "pass": 291,
    "path": "/api/network/sectors",
    "source": "routes/network.js",
    "risks": []
  },
  {
    "pass": 292,
    "path": "/api/network/sites",
    "source": "routes/network.js",
    "risks": []
  }
];

export async function runProbes(ctx) {
  const { probeDemo } = ctx;
  /** @type {Array<Record<string, unknown>>} */
  const probes = [];
  for (const t of TARGETS) {
    probes.push({
      pass: t.pass,
      ...(await probeDemo("GET", t.path)),
      source: t.source || "auto-discover",
      risks: t.risks || [],
    });
  }
  return probes;
}
