/** Auto deepen batch n11e — generated by wisp-fidelity-deepen-auto (D6445). */
export const BATCH_ID = "n11e";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11e";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust GET round n11e (D6445)";
export const AUTO = true;
export const PASSES = [
  { id: 303, title: "Auto GET /api/users/suggest-role" },
  { id: 304, title: "Auto GET /api/users/test" },
  { id: 305, title: "Auto GET /api/work-orders/" },
];
export const REFRESH_PATHS = ["/api/users","/api/work-orders"];
export const TARGETS = [
  {
    "pass": 303,
    "path": "/api/users/suggest-role",
    "source": "routes/users/auto-assign-role.js",
    "risks": []
  },
  {
    "pass": 304,
    "path": "/api/users/test",
    "source": "routes/users/tenants.js",
    "risks": []
  },
  {
    "pass": 305,
    "path": "/api/work-orders/",
    "source": "routes/work-orders.js",
    "risks": []
  }
];

export async function runProbes(ctx) {
  const { probeDemo } = ctx;
  /** @type {Array<Record<string, unknown>>} */
  const probes = [];
  for (const t of TARGETS) {
    probes.push({
      pass: t.pass,
      ...(await probeDemo("GET", t.path)),
      source: t.source || "auto-discover",
      risks: t.risks || [],
    });
  }
  return probes;
}
