/** Auto deepen batch n11f — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11f";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11f";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11f (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 306, title: "Auto GET /admin/tenants/:tenantId" },
  { id: 307, title: "Auto GET /admin/tenants/:tenantId/users" },
  { id: 308, title: "Auto GET /api/auth/check-email-verified/:email" },
  { id: 309, title: "Auto GET /api/billing/invoices/:tenantId" },
  { id: 310, title: "Auto GET /api/billing/payment-methods/:tenantId" },
  { id: 311, title: "Auto GET /api/billing/subscription/:tenantId" },
  { id: 312, title: "Auto GET /api/branding/:tenantId" },
  { id: 313, title: "Auto GET /api/bundles/:id" },
  { id: 314, title: "Auto GET /api/bundles/search/:query" },
  { id: 315, title: "Auto GET /api/bundles/type/:bundleType" },
];
export const REFRESH_PATHS = ["/admin/tenants","/api/auth","/api/billing","/api/branding","/api/bundles"];
export const TARGETS = [
  {
    "pass": 306,
    "method": "GET",
    "template": "/admin/tenants/:tenantId",
    "path": "/admin/tenants/:tenantId",
    "source": "routes/admin/tenants.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 307,
    "method": "GET",
    "template": "/admin/tenants/:tenantId/users",
    "path": "/admin/tenants/:tenantId/users",
    "source": "routes/admin/tenants.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 308,
    "method": "GET",
    "template": "/api/auth/check-email-verified/:email",
    "path": "/api/auth/check-email-verified/:email",
    "source": "routes/auth/verification.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "email/firebase secrets may be unset for outbound notify"
    ]
  },
  {
    "pass": 309,
    "method": "GET",
    "template": "/api/billing/invoices/:tenantId",
    "path": "/api/billing/invoices/:tenantId",
    "source": "billing-api.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "voice carrier / webhook secrets may be unset"
    ]
  },
  {
    "pass": 310,
    "method": "GET",
    "template": "/api/billing/payment-methods/:tenantId",
    "path": "/api/billing/payment-methods/:tenantId",
    "source": "billing-api.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 311,
    "method": "GET",
    "template": "/api/billing/subscription/:tenantId",
    "path": "/api/billing/subscription/:tenantId",
    "source": "billing-api.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 312,
    "method": "GET",
    "template": "/api/branding/:tenantId",
    "path": "/api/branding/:tenantId",
    "source": "routes/branding-api.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "email/firebase secrets may be unset for outbound notify"
    ]
  },
  {
    "pass": 313,
    "method": "GET",
    "template": "/api/bundles/:id",
    "path": "/api/bundles/:id",
    "source": "routes/hardwareBundles.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 314,
    "method": "GET",
    "template": "/api/bundles/search/:query",
    "path": "/api/bundles/search/:query",
    "source": "routes/hardwareBundles.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 315,
    "method": "GET",
    "template": "/api/bundles/type/:bundleType",
    "path": "/api/bundles/type/:bundleType",
    "source": "routes/hardwareBundles.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
