/** Auto deepen batch n11g — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11g";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11g";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11g (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 316, title: "Auto GET /api/customer-billing/:customerId" },
  { id: 317, title: "Auto GET /api/customer-portal/billing/invoices/:invoiceId" },
  { id: 318, title: "Auto GET /api/customer-portal/tickets/:id" },
  { id: 319, title: "Auto GET /api/customers/:id" },
  { id: 320, title: "Auto GET /api/customers/:id/subscriber" },
  { id: 321, title: "Auto GET /api/customers/search/email/:email" },
  { id: 322, title: "Auto GET /api/customers/search/imsi/:imsi" },
  { id: 323, title: "Auto GET /api/customers/search/phone/:phone" },
  { id: 324, title: "Auto GET /api/epc/:epc_id/commands" },
  { id: 325, title: "Auto GET /api/epc/:epc_id/commands/history" },
];
export const REFRESH_PATHS = ["/api/customer-billing","/api/customer-portal","/api/customers","/api/epc"];
export const TARGETS = [
  {
    "pass": 316,
    "method": "GET",
    "template": "/api/customer-billing/:customerId",
    "path": "/api/customer-billing/:customerId",
    "source": "routes/customer-billing.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 317,
    "method": "GET",
    "template": "/api/customer-portal/billing/invoices/:invoiceId",
    "path": "/api/customer-portal/billing/invoices/:invoiceId",
    "source": "routes/customer-portal-api.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "voice carrier / webhook secrets may be unset"
    ]
  },
  {
    "pass": 318,
    "method": "GET",
    "template": "/api/customer-portal/tickets/:id",
    "path": "/api/customer-portal/tickets/:id",
    "source": "routes/customer-portal-api.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 319,
    "method": "GET",
    "template": "/api/customers/:id",
    "path": "/api/customers/:id",
    "source": "routes/customers.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 320,
    "method": "GET",
    "template": "/api/customers/:id/subscriber",
    "path": "/api/customers/:id/subscriber",
    "source": "routes/customers.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 321,
    "method": "GET",
    "template": "/api/customers/search/email/:email",
    "path": "/api/customers/search/email/:email",
    "source": "routes/customers.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "email/firebase secrets may be unset for outbound notify"
    ]
  },
  {
    "pass": 322,
    "method": "GET",
    "template": "/api/customers/search/imsi/:imsi",
    "path": "/api/customers/search/imsi/:imsi",
    "source": "routes/customers.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 323,
    "method": "GET",
    "template": "/api/customers/search/phone/:phone",
    "path": "/api/customers/search/phone/:phone",
    "source": "routes/customers.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 324,
    "method": "GET",
    "template": "/api/epc/:epc_id/commands",
    "path": "/api/epc/:epc_id/commands",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 325,
    "method": "GET",
    "template": "/api/epc/:epc_id/commands/history",
    "path": "/api/epc/:epc_id/commands/history",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
