/** Auto deepen batch n11i — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11i";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11i";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11i (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 336, title: "Auto GET /api/internal/user-tenants/:userId" },
  { id: 337, title: "Auto GET /api/inventory/:id" },
  { id: 338, title: "Auto GET /api/inventory/by-location/:locationType" },
  { id: 339, title: "Auto GET /api/inventory/by-site/:siteId" },
  { id: 340, title: "Auto GET /api/mikrotik/devices/:id" },
  { id: 341, title: "Auto GET /api/mikrotik/devices/:id/credentials" },
  { id: 342, title: "Auto GET /api/mikrotik/devices/:id/metrics" },
  { id: 343, title: "Auto GET /api/monitoring/graphs/ping/:deviceId" },
  { id: 344, title: "Auto GET /api/monitoring/graphs/snmp/:deviceId" },
  { id: 345, title: "Auto GET /api/network/cpe/:id" },
];
export const REFRESH_PATHS = ["/api/internal","/api/inventory","/api/mikrotik","/api/monitoring","/api/network"];
export const TARGETS = [
  {
    "pass": 336,
    "method": "GET",
    "template": "/api/internal/user-tenants/:userId",
    "path": "/api/internal/user-tenants/:userId",
    "source": "routes/internal.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 337,
    "method": "GET",
    "template": "/api/inventory/:id",
    "path": "/api/inventory/:id",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 338,
    "method": "GET",
    "template": "/api/inventory/by-location/:locationType",
    "path": "/api/inventory/by-location/:locationType",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 339,
    "method": "GET",
    "template": "/api/inventory/by-site/:siteId",
    "path": "/api/inventory/by-site/:siteId",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 340,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id",
    "path": "/api/mikrotik/devices/:id",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 341,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/credentials",
    "path": "/api/mikrotik/devices/:id/credentials",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 342,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/metrics",
    "path": "/api/mikrotik/devices/:id/metrics",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 343,
    "method": "GET",
    "template": "/api/monitoring/graphs/ping/:deviceId",
    "path": "/api/monitoring/graphs/ping/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 344,
    "method": "GET",
    "template": "/api/monitoring/graphs/snmp/:deviceId",
    "path": "/api/monitoring/graphs/snmp/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 345,
    "method": "GET",
    "template": "/api/network/cpe/:id",
    "path": "/api/network/cpe/:id",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
