/** Auto deepen batch n11m — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11m";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11m";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get+golden-mut round n11m (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 376, title: "Auto GET /api/users/tenant/:tenantId" },
  { id: 377, title: "Auto GET /api/users/tenant/:tenantId/visible" },
  { id: 378, title: "Auto GET /api/voice/port-orders/:id/events" },
  { id: 379, title: "Auto GET /api/work-orders/:id" },
  { id: 380, title: "Auto GET /api/work-orders/assigned/:userId" },
  { id: 381, title: "Auto GET /api/work-orders/site/:siteId" },
  { id: 382, title: "Auto POST /api/inventory/scan/check-in" },
];
export const REFRESH_PATHS = ["/api/users","/api/voice","/api/work-orders","/api/inventory"];
export const TARGETS = [
  {
    "pass": 376,
    "method": "GET",
    "template": "/api/users/tenant/:tenantId",
    "path": "/api/users/tenant/:tenantId",
    "source": "routes/users/tenant-details.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 377,
    "method": "GET",
    "template": "/api/users/tenant/:tenantId/visible",
    "path": "/api/users/tenant/:tenantId/visible",
    "source": "routes/users/index.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 378,
    "method": "GET",
    "template": "/api/voice/port-orders/:id/events",
    "path": "/api/voice/port-orders/:id/events",
    "source": "routes/voice-sip.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "voice carrier / webhook secrets may be unset"
    ]
  },
  {
    "pass": 379,
    "method": "GET",
    "template": "/api/work-orders/:id",
    "path": "/api/work-orders/:id",
    "source": "routes/work-orders.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 380,
    "method": "GET",
    "template": "/api/work-orders/assigned/:userId",
    "path": "/api/work-orders/assigned/:userId",
    "source": "routes/work-orders.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 381,
    "method": "GET",
    "template": "/api/work-orders/site/:siteId",
    "path": "/api/work-orders/site/:siteId",
    "source": "routes/work-orders.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 382,
    "method": "POST",
    "template": "/api/inventory/scan/check-in",
    "path": "/api/inventory/scan/check-in",
    "source": "routes/inventory.js",
    "tier": "golden-mut",
    "hasParams": false,
    "risks": [],
    "body": null
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
