/** Auto deepen batch n11p — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11p";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11p";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11p (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 403, title: "Auto GET /api/epc/:epc_id/commands" },
  { id: 404, title: "Auto GET /api/epc/:epc_id/commands/history" },
  { id: 405, title: "Auto GET /api/epc/:epc_id/logs" },
  { id: 406, title: "Auto GET /api/epc/:epc_id/status" },
  { id: 407, title: "Auto GET /api/epc/:epc_id/status/history" },
  { id: 408, title: "Auto GET /api/epc/:epcId/metrics/history" },
  { id: 409, title: "Auto GET /api/epc/:epcId/status" },
  { id: 410, title: "Auto GET /api/epc/:id" },
  { id: 411, title: "Auto GET /api/epc/metrics/:id" },
  { id: 412, title: "Auto GET /api/internal/user-tenants/:userId" },
];
export const REFRESH_PATHS = ["/api/epc","/api/internal"];
export const TARGETS = [
  {
    "pass": 403,
    "method": "GET",
    "template": "/api/epc/:epc_id/commands",
    "path": "/api/epc/:epc_id/commands",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 404,
    "method": "GET",
    "template": "/api/epc/:epc_id/commands/history",
    "path": "/api/epc/:epc_id/commands/history",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 405,
    "method": "GET",
    "template": "/api/epc/:epc_id/logs",
    "path": "/api/epc/:epc_id/logs",
    "source": "routes/epc-logs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 406,
    "method": "GET",
    "template": "/api/epc/:epc_id/status",
    "path": "/api/epc/:epc_id/status",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 407,
    "method": "GET",
    "template": "/api/epc/:epc_id/status/history",
    "path": "/api/epc/:epc_id/status/history",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 408,
    "method": "GET",
    "template": "/api/epc/:epcId/metrics/history",
    "path": "/api/epc/:epcId/metrics/history",
    "source": "routes/epcMetrics.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 409,
    "method": "GET",
    "template": "/api/epc/:epcId/status",
    "path": "/api/epc/:epcId/status",
    "source": "routes/epcMetrics.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 410,
    "method": "GET",
    "template": "/api/epc/:id",
    "path": "/api/epc/:id",
    "source": "routes/epc.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 411,
    "method": "GET",
    "template": "/api/epc/metrics/:id",
    "path": "/api/epc/metrics/:id",
    "source": "routes/epc.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 412,
    "method": "GET",
    "template": "/api/internal/user-tenants/:userId",
    "path": "/api/internal/user-tenants/:userId",
    "source": "routes/internal.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
