/** Auto deepen batch n11s — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11s";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11s";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11s (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 433, title: "Auto GET /api/network/sites/:siteId/hardware" },
  { id: 434, title: "Auto GET /api/network/sites/:siteId/sectors" },
  { id: 435, title: "Auto GET /api/permissions/role/:role" },
  { id: 436, title: "Auto GET /api/permissions/user/:userId" },
  { id: 437, title: "Auto GET /api/plans/:id/marketing/addresses" },
  { id: 438, title: "Auto GET /api/plans/:id/marketing/progress/:requestId" },
  { id: 439, title: "Auto GET /api/plans/:id/missing-hardware" },
  { id: 440, title: "Auto GET /api/plans/:id/sites" },
  { id: 441, title: "Auto GET /api/plans/deployment-photos/:planId/:fileId" },
  { id: 442, title: "Auto GET /api/plans/mobile/:userId" },
];
export const REFRESH_PATHS = ["/api/network","/api/permissions","/api/plans"];
export const TARGETS = [
  {
    "pass": 433,
    "method": "GET",
    "template": "/api/network/sites/:siteId/hardware",
    "path": "/api/network/sites/:siteId/hardware",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 434,
    "method": "GET",
    "template": "/api/network/sites/:siteId/sectors",
    "path": "/api/network/sites/:siteId/sectors",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 435,
    "method": "GET",
    "template": "/api/permissions/role/:role",
    "path": "/api/permissions/role/:role",
    "source": "routes/permissions.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 436,
    "method": "GET",
    "template": "/api/permissions/user/:userId",
    "path": "/api/permissions/user/:userId",
    "source": "routes/permissions.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 437,
    "method": "GET",
    "template": "/api/plans/:id/marketing/addresses",
    "path": "/api/plans/:id/marketing/addresses",
    "source": "routes/plans/plans-marketing.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 438,
    "method": "GET",
    "template": "/api/plans/:id/marketing/progress/:requestId",
    "path": "/api/plans/:id/marketing/progress/:requestId",
    "source": "routes/plans/plans-marketing.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 439,
    "method": "GET",
    "template": "/api/plans/:id/missing-hardware",
    "path": "/api/plans/:id/missing-hardware",
    "source": "routes/plans/plans-hardware.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 440,
    "method": "GET",
    "template": "/api/plans/:id/sites",
    "path": "/api/plans/:id/sites",
    "source": "routes/plans/plans-features.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 441,
    "method": "GET",
    "template": "/api/plans/deployment-photos/:planId/:fileId",
    "path": "/api/plans/deployment-photos/:planId/:fileId",
    "source": "routes/plans/plans-deployment-photos.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 442,
    "method": "GET",
    "template": "/api/plans/mobile/:userId",
    "path": "/api/plans/mobile/:userId",
    "source": "routes/plans/plans-mobile.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
