/** Auto deepen batch n11u — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11u";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11u";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11u (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 453, title: "Auto GET /api/portal/domain/:domain" },
  { id: 454, title: "Auto GET /api/portal/subdomain/:subdomain" },
  { id: 455, title: "Auto GET /api/subcontractors/:id" },
  { id: 456, title: "Auto GET /api/subcontractors/:id/expired-items" },
  { id: 457, title: "Auto GET /api/users/:userId" },
  { id: 458, title: "Auto GET /api/users/:userId/activity" },
  { id: 459, title: "Auto GET /api/voice/port-orders/:id/events" },
  { id: 460, title: "Auto GET /api/work-orders/site/:siteId" },
];
export const REFRESH_PATHS = ["/api/portal","/api/subcontractors","/api/users","/api/voice","/api/work-orders"];
export const TARGETS = [
  {
    "pass": 453,
    "method": "GET",
    "template": "/api/portal/domain/:domain",
    "path": "/api/portal/domain/:domain",
    "source": "routes/portal-domain.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 454,
    "method": "GET",
    "template": "/api/portal/subdomain/:subdomain",
    "path": "/api/portal/subdomain/:subdomain",
    "source": "routes/portal-domain.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 455,
    "method": "GET",
    "template": "/api/subcontractors/:id",
    "path": "/api/subcontractors/:id",
    "source": "routes/subcontractors.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 456,
    "method": "GET",
    "template": "/api/subcontractors/:id/expired-items",
    "path": "/api/subcontractors/:id/expired-items",
    "source": "routes/subcontractors.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 457,
    "method": "GET",
    "template": "/api/users/:userId",
    "path": "/api/users/:userId",
    "source": "routes/users/tenants.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 458,
    "method": "GET",
    "template": "/api/users/:userId/activity",
    "path": "/api/users/:userId/activity",
    "source": "routes/users/index.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 459,
    "method": "GET",
    "template": "/api/voice/port-orders/:id/events",
    "path": "/api/voice/port-orders/:id/events",
    "source": "routes/voice-sip.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "voice carrier / webhook secrets may be unset"
    ]
  },
  {
    "pass": 460,
    "method": "GET",
    "template": "/api/work-orders/site/:siteId",
    "path": "/api/work-orders/site/:siteId",
    "source": "routes/work-orders.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
