/** Auto deepen batch n11w — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11w";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11w";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11w (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 471, title: "Auto GET /api/epc/:epc_id/commands" },
  { id: 472, title: "Auto GET /api/epc/:epc_id/commands/history" },
  { id: 473, title: "Auto GET /api/epc/:epc_id/logs" },
  { id: 474, title: "Auto GET /api/epc/:epc_id/status" },
  { id: 475, title: "Auto GET /api/epc/:epc_id/status/history" },
  { id: 476, title: "Auto GET /api/epc/:epcId/metrics/history" },
  { id: 477, title: "Auto GET /api/epc/:epcId/status" },
  { id: 478, title: "Auto GET /api/epc/:id" },
  { id: 479, title: "Auto GET /api/epc/metrics/:id" },
  { id: 480, title: "Auto GET /api/internal/user-tenants/:userId" },
];
export const REFRESH_PATHS = ["/api/epc","/api/internal"];
export const TARGETS = [
  {
    "pass": 471,
    "method": "GET",
    "template": "/api/epc/:epc_id/commands",
    "path": "/api/epc/:epc_id/commands",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 472,
    "method": "GET",
    "template": "/api/epc/:epc_id/commands/history",
    "path": "/api/epc/:epc_id/commands/history",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 473,
    "method": "GET",
    "template": "/api/epc/:epc_id/logs",
    "path": "/api/epc/:epc_id/logs",
    "source": "routes/epc-logs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 474,
    "method": "GET",
    "template": "/api/epc/:epc_id/status",
    "path": "/api/epc/:epc_id/status",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 475,
    "method": "GET",
    "template": "/api/epc/:epc_id/status/history",
    "path": "/api/epc/:epc_id/status/history",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 476,
    "method": "GET",
    "template": "/api/epc/:epcId/metrics/history",
    "path": "/api/epc/:epcId/metrics/history",
    "source": "routes/epcMetrics.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 477,
    "method": "GET",
    "template": "/api/epc/:epcId/status",
    "path": "/api/epc/:epcId/status",
    "source": "routes/epcMetrics.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 478,
    "method": "GET",
    "template": "/api/epc/:id",
    "path": "/api/epc/:id",
    "source": "routes/epc.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 479,
    "method": "GET",
    "template": "/api/epc/metrics/:id",
    "path": "/api/epc/metrics/:id",
    "source": "routes/epc.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 480,
    "method": "GET",
    "template": "/api/internal/user-tenants/:userId",
    "path": "/api/internal/user-tenants/:userId",
    "source": "routes/internal.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
