/** Auto deepen batch n11x — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11x";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11x";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11x (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 481, title: "Auto GET /api/inventory/by-location/:locationType" },
  { id: 482, title: "Auto GET /api/inventory/by-site/:siteId" },
  { id: 483, title: "Auto GET /api/mikrotik/devices/:id" },
  { id: 484, title: "Auto GET /api/mikrotik/devices/:id/credentials" },
  { id: 485, title: "Auto GET /api/mikrotik/devices/:id/metrics" },
  { id: 486, title: "Auto GET /api/monitoring/graphs/ping/:deviceId" },
  { id: 487, title: "Auto GET /api/monitoring/graphs/snmp/:deviceId" },
  { id: 488, title: "Auto GET /api/network/sites/:siteId/hardware" },
  { id: 489, title: "Auto GET /api/network/sites/:siteId/sectors" },
  { id: 490, title: "Auto GET /api/permissions/role/:role" },
];
export const REFRESH_PATHS = ["/api/inventory","/api/mikrotik","/api/monitoring","/api/network","/api/permissions"];
export const TARGETS = [
  {
    "pass": 481,
    "method": "GET",
    "template": "/api/inventory/by-location/:locationType",
    "path": "/api/inventory/by-location/:locationType",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 482,
    "method": "GET",
    "template": "/api/inventory/by-site/:siteId",
    "path": "/api/inventory/by-site/:siteId",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 483,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id",
    "path": "/api/mikrotik/devices/:id",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 484,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/credentials",
    "path": "/api/mikrotik/devices/:id/credentials",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 485,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/metrics",
    "path": "/api/mikrotik/devices/:id/metrics",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 486,
    "method": "GET",
    "template": "/api/monitoring/graphs/ping/:deviceId",
    "path": "/api/monitoring/graphs/ping/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 487,
    "method": "GET",
    "template": "/api/monitoring/graphs/snmp/:deviceId",
    "path": "/api/monitoring/graphs/snmp/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 488,
    "method": "GET",
    "template": "/api/network/sites/:siteId/hardware",
    "path": "/api/network/sites/:siteId/hardware",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 489,
    "method": "GET",
    "template": "/api/network/sites/:siteId/sectors",
    "path": "/api/network/sites/:siteId/sectors",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 490,
    "method": "GET",
    "template": "/api/permissions/role/:role",
    "path": "/api/permissions/role/:role",
    "source": "routes/permissions.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
