/** Auto deepen batch n11z — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11z";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11z";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11z (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 501, title: "Auto GET /api/epc/:epc_id/commands" },
  { id: 502, title: "Auto GET /api/epc/:epc_id/commands/history" },
  { id: 503, title: "Auto GET /api/epc/:epc_id/logs" },
  { id: 504, title: "Auto GET /api/epc/:epc_id/status" },
  { id: 505, title: "Auto GET /api/epc/:epc_id/status/history" },
  { id: 506, title: "Auto GET /api/epc/:epcId/metrics/history" },
  { id: 507, title: "Auto GET /api/epc/:epcId/status" },
  { id: 508, title: "Auto GET /api/epc/:id" },
  { id: 509, title: "Auto GET /api/epc/metrics/:id" },
  { id: 510, title: "Auto GET /api/internal/user-tenants/:userId" },
];
export const REFRESH_PATHS = ["/api/epc","/api/internal"];
export const TARGETS = [
  {
    "pass": 501,
    "method": "GET",
    "template": "/api/epc/:epc_id/commands",
    "path": "/api/epc/:epc_id/commands",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 502,
    "method": "GET",
    "template": "/api/epc/:epc_id/commands/history",
    "path": "/api/epc/:epc_id/commands/history",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 503,
    "method": "GET",
    "template": "/api/epc/:epc_id/logs",
    "path": "/api/epc/:epc_id/logs",
    "source": "routes/epc-logs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 504,
    "method": "GET",
    "template": "/api/epc/:epc_id/status",
    "path": "/api/epc/:epc_id/status",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 505,
    "method": "GET",
    "template": "/api/epc/:epc_id/status/history",
    "path": "/api/epc/:epc_id/status/history",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 506,
    "method": "GET",
    "template": "/api/epc/:epcId/metrics/history",
    "path": "/api/epc/:epcId/metrics/history",
    "source": "routes/epcMetrics.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 507,
    "method": "GET",
    "template": "/api/epc/:epcId/status",
    "path": "/api/epc/:epcId/status",
    "source": "routes/epcMetrics.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 508,
    "method": "GET",
    "template": "/api/epc/:id",
    "path": "/api/epc/:id",
    "source": "routes/epc.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 509,
    "method": "GET",
    "template": "/api/epc/metrics/:id",
    "path": "/api/epc/metrics/:id",
    "source": "routes/epc.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 510,
    "method": "GET",
    "template": "/api/internal/user-tenants/:userId",
    "path": "/api/internal/user-tenants/:userId",
    "source": "routes/internal.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
