/** Auto deepen batch n12a — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n12a";
export const KIND = "chrysalis.wisp.fidelity-deepen-n12a";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n12a (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 511, title: "Auto GET /api/inventory/by-location/:locationType" },
  { id: 512, title: "Auto GET /api/inventory/by-site/:siteId" },
  { id: 513, title: "Auto GET /api/mikrotik/devices/:id" },
  { id: 514, title: "Auto GET /api/mikrotik/devices/:id/credentials" },
  { id: 515, title: "Auto GET /api/mikrotik/devices/:id/metrics" },
  { id: 516, title: "Auto GET /api/monitoring/graphs/ping/:deviceId" },
  { id: 517, title: "Auto GET /api/monitoring/graphs/snmp/:deviceId" },
  { id: 518, title: "Auto GET /api/network/sites/:siteId/hardware" },
  { id: 519, title: "Auto GET /api/network/sites/:siteId/sectors" },
  { id: 520, title: "Auto GET /api/permissions/role/:role" },
];
export const REFRESH_PATHS = ["/api/inventory","/api/mikrotik","/api/monitoring","/api/network","/api/permissions"];
export const TARGETS = [
  {
    "pass": 511,
    "method": "GET",
    "template": "/api/inventory/by-location/:locationType",
    "path": "/api/inventory/by-location/:locationType",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 512,
    "method": "GET",
    "template": "/api/inventory/by-site/:siteId",
    "path": "/api/inventory/by-site/:siteId",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 513,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id",
    "path": "/api/mikrotik/devices/:id",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 514,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/credentials",
    "path": "/api/mikrotik/devices/:id/credentials",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 515,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/metrics",
    "path": "/api/mikrotik/devices/:id/metrics",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 516,
    "method": "GET",
    "template": "/api/monitoring/graphs/ping/:deviceId",
    "path": "/api/monitoring/graphs/ping/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 517,
    "method": "GET",
    "template": "/api/monitoring/graphs/snmp/:deviceId",
    "path": "/api/monitoring/graphs/snmp/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 518,
    "method": "GET",
    "template": "/api/network/sites/:siteId/hardware",
    "path": "/api/network/sites/:siteId/hardware",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 519,
    "method": "GET",
    "template": "/api/network/sites/:siteId/sectors",
    "path": "/api/network/sites/:siteId/sectors",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 520,
    "method": "GET",
    "template": "/api/permissions/role/:role",
    "path": "/api/permissions/role/:role",
    "source": "routes/permissions.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
