/** Auto deepen batch n12b — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n12b";
export const KIND = "chrysalis.wisp.fidelity-deepen-n12b";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n12b (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 521, title: "Auto GET /api/auth/check-email-verified/:email" },
  { id: 522, title: "Auto GET /api/bundles/search/:query" },
  { id: 523, title: "Auto GET /api/bundles/type/:bundleType" },
  { id: 524, title: "Auto GET /api/customer-billing/:customerId" },
  { id: 525, title: "Auto GET /api/customer-portal/billing/invoices/:invoiceId" },
  { id: 526, title: "Auto GET /api/customer-portal/tickets/:id" },
  { id: 527, title: "Auto GET /api/customers/:id/subscriber" },
  { id: 528, title: "Auto GET /api/customers/search/email/:email" },
  { id: 529, title: "Auto GET /api/customers/search/imsi/:imsi" },
  { id: 530, title: "Auto GET /api/customers/search/phone/:phone" },
];
export const REFRESH_PATHS = ["/api/auth","/api/bundles","/api/customer-billing","/api/customer-portal","/api/customers"];
export const TARGETS = [
  {
    "pass": 521,
    "method": "GET",
    "template": "/api/auth/check-email-verified/:email",
    "path": "/api/auth/check-email-verified/:email",
    "source": "routes/auth/verification.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "email/firebase secrets may be unset for outbound notify"
    ]
  },
  {
    "pass": 522,
    "method": "GET",
    "template": "/api/bundles/search/:query",
    "path": "/api/bundles/search/:query",
    "source": "routes/hardwareBundles.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 523,
    "method": "GET",
    "template": "/api/bundles/type/:bundleType",
    "path": "/api/bundles/type/:bundleType",
    "source": "routes/hardwareBundles.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 524,
    "method": "GET",
    "template": "/api/customer-billing/:customerId",
    "path": "/api/customer-billing/:customerId",
    "source": "routes/customer-billing.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 525,
    "method": "GET",
    "template": "/api/customer-portal/billing/invoices/:invoiceId",
    "path": "/api/customer-portal/billing/invoices/:invoiceId",
    "source": "routes/customer-portal-api.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "voice carrier / webhook secrets may be unset"
    ]
  },
  {
    "pass": 526,
    "method": "GET",
    "template": "/api/customer-portal/tickets/:id",
    "path": "/api/customer-portal/tickets/:id",
    "source": "routes/customer-portal-api.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 527,
    "method": "GET",
    "template": "/api/customers/:id/subscriber",
    "path": "/api/customers/:id/subscriber",
    "source": "routes/customers.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 528,
    "method": "GET",
    "template": "/api/customers/search/email/:email",
    "path": "/api/customers/search/email/:email",
    "source": "routes/customers.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "email/firebase secrets may be unset for outbound notify"
    ]
  },
  {
    "pass": 529,
    "method": "GET",
    "template": "/api/customers/search/imsi/:imsi",
    "path": "/api/customers/search/imsi/:imsi",
    "source": "routes/customers.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 530,
    "method": "GET",
    "template": "/api/customers/search/phone/:phone",
    "path": "/api/customers/search/phone/:phone",
    "source": "routes/customers.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
