/** Auto deepen batch n12d — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n12d";
export const KIND = "chrysalis.wisp.fidelity-deepen-n12d";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n12d (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 541, title: "Auto GET /api/inventory/by-location/:locationType" },
  { id: 542, title: "Auto GET /api/inventory/by-site/:siteId" },
  { id: 543, title: "Auto GET /api/mikrotik/devices/:id" },
  { id: 544, title: "Auto GET /api/mikrotik/devices/:id/credentials" },
  { id: 545, title: "Auto GET /api/mikrotik/devices/:id/metrics" },
  { id: 546, title: "Auto GET /api/monitoring/graphs/ping/:deviceId" },
  { id: 547, title: "Auto GET /api/monitoring/graphs/snmp/:deviceId" },
  { id: 548, title: "Auto GET /api/network/sites/:siteId/hardware" },
  { id: 549, title: "Auto GET /api/network/sites/:siteId/sectors" },
  { id: 550, title: "Auto GET /api/permissions/role/:role" },
];
export const REFRESH_PATHS = ["/api/inventory","/api/mikrotik","/api/monitoring","/api/network","/api/permissions"];
export const TARGETS = [
  {
    "pass": 541,
    "method": "GET",
    "template": "/api/inventory/by-location/:locationType",
    "path": "/api/inventory/by-location/:locationType",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 542,
    "method": "GET",
    "template": "/api/inventory/by-site/:siteId",
    "path": "/api/inventory/by-site/:siteId",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 543,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id",
    "path": "/api/mikrotik/devices/:id",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 544,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/credentials",
    "path": "/api/mikrotik/devices/:id/credentials",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 545,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/metrics",
    "path": "/api/mikrotik/devices/:id/metrics",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 546,
    "method": "GET",
    "template": "/api/monitoring/graphs/ping/:deviceId",
    "path": "/api/monitoring/graphs/ping/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 547,
    "method": "GET",
    "template": "/api/monitoring/graphs/snmp/:deviceId",
    "path": "/api/monitoring/graphs/snmp/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 548,
    "method": "GET",
    "template": "/api/network/sites/:siteId/hardware",
    "path": "/api/network/sites/:siteId/hardware",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 549,
    "method": "GET",
    "template": "/api/network/sites/:siteId/sectors",
    "path": "/api/network/sites/:siteId/sectors",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 550,
    "method": "GET",
    "template": "/api/permissions/role/:role",
    "path": "/api/permissions/role/:role",
    "source": "routes/permissions.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
