/** Auto deepen batch n10z — generated by wisp-fidelity-deepen-auto (D6445). */
export const BATCH_ID = "n10z";
export const KIND = "chrysalis.wisp.fidelity-deepen-n10z";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust GET round n10z (D6445)";
export const AUTO = true;
export const PASSES = [
  { id: 253, title: "Auto GET /admin/" },
  { id: 254, title: "Auto GET /admin/tenants/" },
  { id: 255, title: "Auto GET /api/agent/manifest" },
  { id: 256, title: "Auto GET /api/auth/me" },
  { id: 257, title: "Auto GET /api/auth/status" },
  { id: 258, title: "Auto GET /api/billing/analytics" },
  { id: 259, title: "Auto GET /api/billing/invoices" },
  { id: 260, title: "Auto GET /api/billing/payment-methods" },
  { id: 261, title: "Auto GET /api/billing/plans" },
  { id: 262, title: "Auto GET /api/billing/subscriptions" },
];
export const REFRESH_PATHS = ["/admin","/admin/tenants","/api/agent","/api/auth","/api/billing"];
export const TARGETS = [
  {
    "pass": 253,
    "path": "/admin/",
    "source": "routes/admin/general.js",
    "risks": []
  },
  {
    "pass": 254,
    "path": "/admin/tenants/",
    "source": "routes/admin/tenants.js",
    "risks": []
  },
  {
    "pass": 255,
    "path": "/api/agent/manifest",
    "source": "routes/agent.js",
    "risks": []
  },
  {
    "pass": 256,
    "path": "/api/auth/me",
    "source": "routes/auth/index.js",
    "risks": []
  },
  {
    "pass": 257,
    "path": "/api/auth/status",
    "source": "routes/auth/index.js",
    "risks": []
  },
  {
    "pass": 258,
    "path": "/api/billing/analytics",
    "source": "billing-api.js",
    "risks": []
  },
  {
    "pass": 259,
    "path": "/api/billing/invoices",
    "source": "billing-api.js",
    "risks": [
      "voice carrier / webhook secrets may be unset"
    ]
  },
  {
    "pass": 260,
    "path": "/api/billing/payment-methods",
    "source": "billing-api.js",
    "risks": []
  },
  {
    "pass": 261,
    "path": "/api/billing/plans",
    "source": "billing-api.js",
    "risks": []
  },
  {
    "pass": 262,
    "path": "/api/billing/subscriptions",
    "source": "billing-api.js",
    "risks": []
  }
];

export async function runProbes(ctx) {
  const { probeDemo } = ctx;
  /** @type {Array<Record<string, unknown>>} */
  const probes = [];
  for (const t of TARGETS) {
    probes.push({
      pass: t.pass,
      ...(await probeDemo("GET", t.path)),
      source: t.source || "auto-discover",
      risks: t.risks || [],
    });
  }
  return probes;
}
