/** Auto deepen batch n11d — generated by wisp-fidelity-deepen-auto (D6445). */
export const BATCH_ID = "n11d";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11d";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust GET round n11d (D6445)";
export const AUTO = true;
export const PASSES = [
  { id: 293, title: "Auto GET /api/notifications/" },
  { id: 294, title: "Auto GET /api/permissions/check" },
  { id: 295, title: "Auto GET /api/permissions/roles" },
  { id: 296, title: "Auto GET /api/plans/" },
  { id: 297, title: "Auto GET /api/plans/hardware/existing" },
  { id: 298, title: "Auto GET /api/subcontractors/" },
  { id: 299, title: "Auto GET /api/system/resources" },
  { id: 300, title: "Auto GET /api/system/services/status" },
  { id: 301, title: "Auto GET /api/tenant-settings/" },
  { id: 302, title: "Auto GET /api/users/" },
];
export const REFRESH_PATHS = ["/api/notifications","/api/permissions","/api/plans","/api/subcontractors","/api/system","/api/tenant-settings","/api/users"];
export const TARGETS = [
  {
    "pass": 293,
    "path": "/api/notifications/",
    "source": "routes/notifications.js",
    "risks": [
      "email/firebase secrets may be unset for outbound notify"
    ]
  },
  {
    "pass": 294,
    "path": "/api/permissions/check",
    "source": "routes/permissions.js",
    "risks": []
  },
  {
    "pass": 295,
    "path": "/api/permissions/roles",
    "source": "routes/permissions.js",
    "risks": []
  },
  {
    "pass": 296,
    "path": "/api/plans/",
    "source": "routes/plans/plans-core.js",
    "risks": []
  },
  {
    "pass": 297,
    "path": "/api/plans/hardware/existing",
    "source": "routes/plans/plans-hardware.js",
    "risks": []
  },
  {
    "pass": 298,
    "path": "/api/subcontractors/",
    "source": "routes/subcontractors.js",
    "risks": []
  },
  {
    "pass": 299,
    "path": "/api/system/resources",
    "source": "routes/system.js",
    "risks": []
  },
  {
    "pass": 300,
    "path": "/api/system/services/status",
    "source": "routes/system.js",
    "risks": []
  },
  {
    "pass": 301,
    "path": "/api/tenant-settings/",
    "source": "routes/tenant-settings.js",
    "risks": []
  },
  {
    "pass": 302,
    "path": "/api/users/",
    "source": "routes/users/index.js",
    "risks": []
  }
];

export async function runProbes(ctx) {
  const { probeDemo } = ctx;
  /** @type {Array<Record<string, unknown>>} */
  const probes = [];
  for (const t of TARGETS) {
    probes.push({
      pass: t.pass,
      ...(await probeDemo("GET", t.path)),
      source: t.source || "auto-discover",
      risks: t.risks || [],
    });
  }
  return probes;
}
