/** Auto deepen batch n11h — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11h";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11h";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11h (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 326, title: "Auto GET /api/epc/:epc_id/logs" },
  { id: 327, title: "Auto GET /api/epc/:epc_id/status" },
  { id: 328, title: "Auto GET /api/epc/:epc_id/status/history" },
  { id: 329, title: "Auto GET /api/epc/:epcId/metrics/history" },
  { id: 330, title: "Auto GET /api/epc/:epcId/status" },
  { id: 331, title: "Auto GET /api/epc/:id" },
  { id: 332, title: "Auto GET /api/epc/metrics/:id" },
  { id: 333, title: "Auto GET /api/incidents/:id" },
  { id: 334, title: "Auto GET /api/installation-documentation/:id" },
  { id: 335, title: "Auto GET /api/internal/tenant-details/:tenantId" },
];
export const REFRESH_PATHS = ["/api/epc","/api/incidents","/api/installation-documentation","/api/internal"];
export const TARGETS = [
  {
    "pass": 326,
    "method": "GET",
    "template": "/api/epc/:epc_id/logs",
    "path": "/api/epc/:epc_id/logs",
    "source": "routes/epc-logs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 327,
    "method": "GET",
    "template": "/api/epc/:epc_id/status",
    "path": "/api/epc/:epc_id/status",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 328,
    "method": "GET",
    "template": "/api/epc/:epc_id/status/history",
    "path": "/api/epc/:epc_id/status/history",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 329,
    "method": "GET",
    "template": "/api/epc/:epcId/metrics/history",
    "path": "/api/epc/:epcId/metrics/history",
    "source": "routes/epcMetrics.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 330,
    "method": "GET",
    "template": "/api/epc/:epcId/status",
    "path": "/api/epc/:epcId/status",
    "source": "routes/epcMetrics.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 331,
    "method": "GET",
    "template": "/api/epc/:id",
    "path": "/api/epc/:id",
    "source": "routes/epc.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 332,
    "method": "GET",
    "template": "/api/epc/metrics/:id",
    "path": "/api/epc/metrics/:id",
    "source": "routes/epc.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 333,
    "method": "GET",
    "template": "/api/incidents/:id",
    "path": "/api/incidents/:id",
    "source": "routes/incidents.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 334,
    "method": "GET",
    "template": "/api/installation-documentation/:id",
    "path": "/api/installation-documentation/:id",
    "source": "routes/installation-documentation.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 335,
    "method": "GET",
    "template": "/api/internal/tenant-details/:tenantId",
    "path": "/api/internal/tenant-details/:tenantId",
    "source": "routes/internal.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
