/** Auto deepen batch n11j — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11j";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11j";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11j (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 346, title: "Auto GET /api/network/sectors/:id" },
  { id: 347, title: "Auto GET /api/network/sites/:id" },
  { id: 348, title: "Auto GET /api/network/sites/:siteId/hardware" },
  { id: 349, title: "Auto GET /api/network/sites/:siteId/sectors" },
  { id: 350, title: "Auto GET /api/permissions/role/:role" },
  { id: 351, title: "Auto GET /api/permissions/user/:userId" },
  { id: 352, title: "Auto GET /api/plans/:id" },
  { id: 353, title: "Auto GET /api/plans/:id/features" },
  { id: 354, title: "Auto GET /api/plans/:id/marketing/addresses" },
  { id: 355, title: "Auto GET /api/plans/:id/marketing/progress/:requestId" },
];
export const REFRESH_PATHS = ["/api/network","/api/permissions","/api/plans"];
export const TARGETS = [
  {
    "pass": 346,
    "method": "GET",
    "template": "/api/network/sectors/:id",
    "path": "/api/network/sectors/:id",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 347,
    "method": "GET",
    "template": "/api/network/sites/:id",
    "path": "/api/network/sites/:id",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 348,
    "method": "GET",
    "template": "/api/network/sites/:siteId/hardware",
    "path": "/api/network/sites/:siteId/hardware",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 349,
    "method": "GET",
    "template": "/api/network/sites/:siteId/sectors",
    "path": "/api/network/sites/:siteId/sectors",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 350,
    "method": "GET",
    "template": "/api/permissions/role/:role",
    "path": "/api/permissions/role/:role",
    "source": "routes/permissions.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 351,
    "method": "GET",
    "template": "/api/permissions/user/:userId",
    "path": "/api/permissions/user/:userId",
    "source": "routes/permissions.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 352,
    "method": "GET",
    "template": "/api/plans/:id",
    "path": "/api/plans/:id",
    "source": "routes/plans/plans-core.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 353,
    "method": "GET",
    "template": "/api/plans/:id/features",
    "path": "/api/plans/:id/features",
    "source": "routes/plans/plans-features.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 354,
    "method": "GET",
    "template": "/api/plans/:id/marketing/addresses",
    "path": "/api/plans/:id/marketing/addresses",
    "source": "routes/plans/plans-marketing.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 355,
    "method": "GET",
    "template": "/api/plans/:id/marketing/progress/:requestId",
    "path": "/api/plans/:id/marketing/progress/:requestId",
    "source": "routes/plans/plans-marketing.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
