/** Auto deepen batch n11k — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11k";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11k";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11k (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 356, title: "Auto GET /api/plans/:id/missing-hardware" },
  { id: 357, title: "Auto GET /api/plans/:id/sites" },
  { id: 358, title: "Auto GET /api/plans/deployment-photos/:planId/:fileId" },
  { id: 359, title: "Auto GET /api/plans/mobile/:userId" },
  { id: 360, title: "Auto GET /api/plans/mobile/:userId/:planId" },
  { id: 361, title: "Auto GET /api/portal-content/:tenantId/alerts" },
  { id: 362, title: "Auto GET /api/portal-content/:tenantId/alerts/active" },
  { id: 363, title: "Auto GET /api/portal-content/:tenantId/chat-settings" },
  { id: 364, title: "Auto GET /api/portal-content/:tenantId/faq" },
  { id: 365, title: "Auto GET /api/portal-content/:tenantId/faq/published" },
];
export const REFRESH_PATHS = ["/api/plans","/api/portal-content"];
export const TARGETS = [
  {
    "pass": 356,
    "method": "GET",
    "template": "/api/plans/:id/missing-hardware",
    "path": "/api/plans/:id/missing-hardware",
    "source": "routes/plans/plans-hardware.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 357,
    "method": "GET",
    "template": "/api/plans/:id/sites",
    "path": "/api/plans/:id/sites",
    "source": "routes/plans/plans-features.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 358,
    "method": "GET",
    "template": "/api/plans/deployment-photos/:planId/:fileId",
    "path": "/api/plans/deployment-photos/:planId/:fileId",
    "source": "routes/plans/plans-deployment-photos.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 359,
    "method": "GET",
    "template": "/api/plans/mobile/:userId",
    "path": "/api/plans/mobile/:userId",
    "source": "routes/plans/plans-mobile.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 360,
    "method": "GET",
    "template": "/api/plans/mobile/:userId/:planId",
    "path": "/api/plans/mobile/:userId/:planId",
    "source": "routes/plans/plans-mobile.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 361,
    "method": "GET",
    "template": "/api/portal-content/:tenantId/alerts",
    "path": "/api/portal-content/:tenantId/alerts",
    "source": "routes/portal-content.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 362,
    "method": "GET",
    "template": "/api/portal-content/:tenantId/alerts/active",
    "path": "/api/portal-content/:tenantId/alerts/active",
    "source": "routes/portal-content.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 363,
    "method": "GET",
    "template": "/api/portal-content/:tenantId/chat-settings",
    "path": "/api/portal-content/:tenantId/chat-settings",
    "source": "routes/portal-content.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 364,
    "method": "GET",
    "template": "/api/portal-content/:tenantId/faq",
    "path": "/api/portal-content/:tenantId/faq",
    "source": "routes/portal-content.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 365,
    "method": "GET",
    "template": "/api/portal-content/:tenantId/faq/published",
    "path": "/api/portal-content/:tenantId/faq/published",
    "source": "routes/portal-content.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
