/** Auto deepen batch n11l — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11l";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11l";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11l (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 366, title: "Auto GET /api/portal-content/:tenantId/knowledge-base" },
  { id: 367, title: "Auto GET /api/portal-content/:tenantId/knowledge-base/:articleId" },
  { id: 368, title: "Auto GET /api/portal-content/:tenantId/knowledge-base/published" },
  { id: 369, title: "Auto GET /api/portal/domain/:domain" },
  { id: 370, title: "Auto GET /api/portal/subdomain/:subdomain" },
  { id: 371, title: "Auto GET /api/portal/tenant/:tenantId" },
  { id: 372, title: "Auto GET /api/subcontractors/:id" },
  { id: 373, title: "Auto GET /api/subcontractors/:id/expired-items" },
  { id: 374, title: "Auto GET /api/users/:userId" },
  { id: 375, title: "Auto GET /api/users/:userId/activity" },
];
export const REFRESH_PATHS = ["/api/portal-content","/api/portal","/api/subcontractors","/api/users"];
export const TARGETS = [
  {
    "pass": 366,
    "method": "GET",
    "template": "/api/portal-content/:tenantId/knowledge-base",
    "path": "/api/portal-content/:tenantId/knowledge-base",
    "source": "routes/portal-content.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 367,
    "method": "GET",
    "template": "/api/portal-content/:tenantId/knowledge-base/:articleId",
    "path": "/api/portal-content/:tenantId/knowledge-base/:articleId",
    "source": "routes/portal-content.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 368,
    "method": "GET",
    "template": "/api/portal-content/:tenantId/knowledge-base/published",
    "path": "/api/portal-content/:tenantId/knowledge-base/published",
    "source": "routes/portal-content.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 369,
    "method": "GET",
    "template": "/api/portal/domain/:domain",
    "path": "/api/portal/domain/:domain",
    "source": "routes/portal-domain.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 370,
    "method": "GET",
    "template": "/api/portal/subdomain/:subdomain",
    "path": "/api/portal/subdomain/:subdomain",
    "source": "routes/portal-domain.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 371,
    "method": "GET",
    "template": "/api/portal/tenant/:tenantId",
    "path": "/api/portal/tenant/:tenantId",
    "source": "routes/portal-domain.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 372,
    "method": "GET",
    "template": "/api/subcontractors/:id",
    "path": "/api/subcontractors/:id",
    "source": "routes/subcontractors.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 373,
    "method": "GET",
    "template": "/api/subcontractors/:id/expired-items",
    "path": "/api/subcontractors/:id/expired-items",
    "source": "routes/subcontractors.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 374,
    "method": "GET",
    "template": "/api/users/:userId",
    "path": "/api/users/:userId",
    "source": "routes/users/tenants.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 375,
    "method": "GET",
    "template": "/api/users/:userId/activity",
    "path": "/api/users/:userId/activity",
    "source": "routes/users/index.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
