/** Auto deepen batch n11o — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11o";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11o";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11o (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 393, title: "Auto GET /api/customer-billing/:customerId" },
  { id: 394, title: "Auto GET /api/customer-portal/billing/invoices/:invoiceId" },
  { id: 395, title: "Auto GET /api/customer-portal/tickets/:id" },
  { id: 396, title: "Auto GET /api/epc/:epc_id/commands" },
  { id: 397, title: "Auto GET /api/epc/:epc_id/commands/history" },
  { id: 398, title: "Auto GET /api/epc/:epc_id/logs" },
  { id: 399, title: "Auto GET /api/epc/:epc_id/status" },
  { id: 400, title: "Auto GET /api/epc/:epc_id/status/history" },
  { id: 401, title: "Auto GET /api/epc/:epcId/metrics/history" },
  { id: 402, title: "Auto GET /api/epc/:epcId/status" },
];
export const REFRESH_PATHS = ["/api/customer-billing","/api/customer-portal","/api/epc"];
export const TARGETS = [
  {
    "pass": 393,
    "method": "GET",
    "template": "/api/customer-billing/:customerId",
    "path": "/api/customer-billing/:customerId",
    "source": "routes/customer-billing.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 394,
    "method": "GET",
    "template": "/api/customer-portal/billing/invoices/:invoiceId",
    "path": "/api/customer-portal/billing/invoices/:invoiceId",
    "source": "routes/customer-portal-api.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "voice carrier / webhook secrets may be unset"
    ]
  },
  {
    "pass": 395,
    "method": "GET",
    "template": "/api/customer-portal/tickets/:id",
    "path": "/api/customer-portal/tickets/:id",
    "source": "routes/customer-portal-api.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 396,
    "method": "GET",
    "template": "/api/epc/:epc_id/commands",
    "path": "/api/epc/:epc_id/commands",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 397,
    "method": "GET",
    "template": "/api/epc/:epc_id/commands/history",
    "path": "/api/epc/:epc_id/commands/history",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 398,
    "method": "GET",
    "template": "/api/epc/:epc_id/logs",
    "path": "/api/epc/:epc_id/logs",
    "source": "routes/epc-logs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 399,
    "method": "GET",
    "template": "/api/epc/:epc_id/status",
    "path": "/api/epc/:epc_id/status",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 400,
    "method": "GET",
    "template": "/api/epc/:epc_id/status/history",
    "path": "/api/epc/:epc_id/status/history",
    "source": "routes/epc-commands.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 401,
    "method": "GET",
    "template": "/api/epc/:epcId/metrics/history",
    "path": "/api/epc/:epcId/metrics/history",
    "source": "routes/epcMetrics.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 402,
    "method": "GET",
    "template": "/api/epc/:epcId/status",
    "path": "/api/epc/:epcId/status",
    "source": "routes/epcMetrics.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
