/** Auto deepen batch n11q — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11q";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11q";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11q (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 413, title: "Auto GET /api/epc/:id" },
  { id: 414, title: "Auto GET /api/epc/metrics/:id" },
  { id: 415, title: "Auto GET /api/internal/user-tenants/:userId" },
  { id: 416, title: "Auto GET /api/inventory/by-location/:locationType" },
  { id: 417, title: "Auto GET /api/inventory/by-site/:siteId" },
  { id: 418, title: "Auto GET /api/mikrotik/devices/:id" },
  { id: 419, title: "Auto GET /api/mikrotik/devices/:id/credentials" },
  { id: 420, title: "Auto GET /api/mikrotik/devices/:id/metrics" },
  { id: 421, title: "Auto GET /api/monitoring/graphs/ping/:deviceId" },
  { id: 422, title: "Auto GET /api/monitoring/graphs/snmp/:deviceId" },
];
export const REFRESH_PATHS = ["/api/epc","/api/internal","/api/inventory","/api/mikrotik","/api/monitoring"];
export const TARGETS = [
  {
    "pass": 413,
    "method": "GET",
    "template": "/api/epc/:id",
    "path": "/api/epc/:id",
    "source": "routes/epc.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 414,
    "method": "GET",
    "template": "/api/epc/metrics/:id",
    "path": "/api/epc/metrics/:id",
    "source": "routes/epc.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 415,
    "method": "GET",
    "template": "/api/internal/user-tenants/:userId",
    "path": "/api/internal/user-tenants/:userId",
    "source": "routes/internal.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 416,
    "method": "GET",
    "template": "/api/inventory/by-location/:locationType",
    "path": "/api/inventory/by-location/:locationType",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 417,
    "method": "GET",
    "template": "/api/inventory/by-site/:siteId",
    "path": "/api/inventory/by-site/:siteId",
    "source": "routes/inventory.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 418,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id",
    "path": "/api/mikrotik/devices/:id",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 419,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/credentials",
    "path": "/api/mikrotik/devices/:id/credentials",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 420,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/metrics",
    "path": "/api/mikrotik/devices/:id/metrics",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 421,
    "method": "GET",
    "template": "/api/monitoring/graphs/ping/:deviceId",
    "path": "/api/monitoring/graphs/ping/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 422,
    "method": "GET",
    "template": "/api/monitoring/graphs/snmp/:deviceId",
    "path": "/api/monitoring/graphs/snmp/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
