/** Auto deepen batch n11r — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11r";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11r";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11r (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 423, title: "Auto GET /api/mikrotik/devices/:id" },
  { id: 424, title: "Auto GET /api/mikrotik/devices/:id/credentials" },
  { id: 425, title: "Auto GET /api/mikrotik/devices/:id/metrics" },
  { id: 426, title: "Auto GET /api/monitoring/graphs/ping/:deviceId" },
  { id: 427, title: "Auto GET /api/monitoring/graphs/snmp/:deviceId" },
  { id: 428, title: "Auto GET /api/network/sites/:siteId/hardware" },
  { id: 429, title: "Auto GET /api/network/sites/:siteId/sectors" },
  { id: 430, title: "Auto GET /api/permissions/role/:role" },
  { id: 431, title: "Auto GET /api/permissions/user/:userId" },
  { id: 432, title: "Auto GET /api/plans/:id/features" },
];
export const REFRESH_PATHS = ["/api/mikrotik","/api/monitoring","/api/network","/api/permissions","/api/plans"];
export const TARGETS = [
  {
    "pass": 423,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id",
    "path": "/api/mikrotik/devices/:id",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 424,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/credentials",
    "path": "/api/mikrotik/devices/:id/credentials",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 425,
    "method": "GET",
    "template": "/api/mikrotik/devices/:id/metrics",
    "path": "/api/mikrotik/devices/:id/metrics",
    "source": "routes/mikrotik.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 426,
    "method": "GET",
    "template": "/api/monitoring/graphs/ping/:deviceId",
    "path": "/api/monitoring/graphs/ping/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 427,
    "method": "GET",
    "template": "/api/monitoring/graphs/snmp/:deviceId",
    "path": "/api/monitoring/graphs/snmp/:deviceId",
    "source": "routes/monitoring-graphs.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "hardware credentials are device/tenant-scoped — do not invent"
    ]
  },
  {
    "pass": 428,
    "method": "GET",
    "template": "/api/network/sites/:siteId/hardware",
    "path": "/api/network/sites/:siteId/hardware",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 429,
    "method": "GET",
    "template": "/api/network/sites/:siteId/sectors",
    "path": "/api/network/sites/:siteId/sectors",
    "source": "routes/network.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 430,
    "method": "GET",
    "template": "/api/permissions/role/:role",
    "path": "/api/permissions/role/:role",
    "source": "routes/permissions.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 431,
    "method": "GET",
    "template": "/api/permissions/user/:userId",
    "path": "/api/permissions/user/:userId",
    "source": "routes/permissions.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 432,
    "method": "GET",
    "template": "/api/plans/:id/features",
    "path": "/api/plans/:id/features",
    "source": "routes/plans/plans-features.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
