/** Auto deepen batch n11t — generated by wisp-fidelity-deepen-auto (D6445). */
import { runAutoProbes } from "../wisp-fidelity-deepen-auto.mjs";

export const BATCH_ID = "n11t";
export const KIND = "chrysalis.wisp.fidelity-deepen-n11t";
export const NEED_ADMIN = false;
export const NOTE = "Auto exhaust param-get round n11t (D6445)";
export const AUTO = true;
export const DEMO_TENANT = "6a166eb07089304417ec967a";
export const PASSES = [
  { id: 443, title: "Auto GET /api/plans/:id/missing-hardware" },
  { id: 444, title: "Auto GET /api/plans/mobile/:userId/:planId" },
  { id: 445, title: "Auto GET /api/portal/domain/:domain" },
  { id: 446, title: "Auto GET /api/portal/subdomain/:subdomain" },
  { id: 447, title: "Auto GET /api/subcontractors/:id" },
  { id: 448, title: "Auto GET /api/subcontractors/:id/expired-items" },
  { id: 449, title: "Auto GET /api/users/:userId" },
  { id: 450, title: "Auto GET /api/users/:userId/activity" },
  { id: 451, title: "Auto GET /api/voice/port-orders/:id/events" },
  { id: 452, title: "Auto GET /api/work-orders/assigned/:userId" },
];
export const REFRESH_PATHS = ["/api/plans","/api/portal","/api/subcontractors","/api/users","/api/voice","/api/work-orders"];
export const TARGETS = [
  {
    "pass": 443,
    "method": "GET",
    "template": "/api/plans/:id/missing-hardware",
    "path": "/api/plans/:id/missing-hardware",
    "source": "routes/plans/plans-hardware.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 444,
    "method": "GET",
    "template": "/api/plans/mobile/:userId/:planId",
    "path": "/api/plans/mobile/:userId/:planId",
    "source": "routes/plans/plans-mobile.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 445,
    "method": "GET",
    "template": "/api/portal/domain/:domain",
    "path": "/api/portal/domain/:domain",
    "source": "routes/portal-domain.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 446,
    "method": "GET",
    "template": "/api/portal/subdomain/:subdomain",
    "path": "/api/portal/subdomain/:subdomain",
    "source": "routes/portal-domain.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 447,
    "method": "GET",
    "template": "/api/subcontractors/:id",
    "path": "/api/subcontractors/:id",
    "source": "routes/subcontractors.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 448,
    "method": "GET",
    "template": "/api/subcontractors/:id/expired-items",
    "path": "/api/subcontractors/:id/expired-items",
    "source": "routes/subcontractors.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 449,
    "method": "GET",
    "template": "/api/users/:userId",
    "path": "/api/users/:userId",
    "source": "routes/users/tenants.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 450,
    "method": "GET",
    "template": "/api/users/:userId/activity",
    "path": "/api/users/:userId/activity",
    "source": "routes/users/index.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  },
  {
    "pass": 451,
    "method": "GET",
    "template": "/api/voice/port-orders/:id/events",
    "path": "/api/voice/port-orders/:id/events",
    "source": "routes/voice-sip.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": [
      "voice carrier / webhook secrets may be unset"
    ]
  },
  {
    "pass": 452,
    "method": "GET",
    "template": "/api/work-orders/assigned/:userId",
    "path": "/api/work-orders/assigned/:userId",
    "source": "routes/work-orders.js",
    "tier": "param-get",
    "hasParams": true,
    "risks": []
  }
];

export async function runProbes(ctx) {
  return runAutoProbes(ctx, TARGETS);
}
