#!/usr/bin/env bash
# Native oracle replay toolchain for GCE (javac, go, ruby, dotnet, hub Python venv).
set -euo pipefail

ENV_FILE="${HOME}/.chrysalis/gce-hub-env.sh"
MARKER="${HOME}/.chrysalis/native-oracle-deps.ok"
VENV="${HOME}/.chrysalis/hub-python-venv"

if [[ "${CHRYSALIS_SKIP_NATIVE_ORACLE_DEPS:-}" == "1" ]]; then
  echo "[gce-install-native-oracle-deps] skip (CHRYSALIS_SKIP_NATIVE_ORACLE_DEPS=1)"
  exit 0
fi

ensure_python_venv() {
  if [[ ! -d "${VENV}" ]]; then
    python3 -m venv "${VENV}"
  fi
  "${VENV}/bin/pip" install -q --upgrade pip
  "${VENV}/bin/pip" install -q "flask>=3.0"
}

install_go_122() {
  local go_ver="1.22.5"
  local go_root="/usr/local/go"
  if [[ -x "${go_root}/bin/go" ]]; then
    local installed
    installed="$("${go_root}/bin/go" version 2>/dev/null || true)"
    if [[ "${installed}" == *"go1.22"* || "${installed}" == *"go1.23"* || "${installed}" == *"go1.24"* ]]; then
      return 0
    fi
  fi
  local arch="amd64"
  case "$(uname -m)" in
    aarch64|arm64) arch="arm64" ;;
  esac
  local tgz="/tmp/go${go_ver}.linux-${arch}.tar.gz"
  curl -fsSL "https://go.dev/dl/go${go_ver}.linux-${arch}.tar.gz" -o "${tgz}"
  sudo rm -rf "${go_root}"
  sudo tar -C /usr/local -xzf "${tgz}"
  rm -f "${tgz}"
}

ensure_ruby_gems() {
  export GEM_HOME="${HOME}/.chrysalis/ruby-gems"
  export PATH="${GEM_HOME}/bin:${PATH}"
  mkdir -p "${GEM_HOME}"
  if ! ruby -e "require 'sinatra/base'; require 'sinatra/json'; require 'rack/test'" 2>/dev/null; then
    gem install sinatra sinatra-contrib rack-test --no-document --install-dir "${GEM_HOME}"
  fi
}

write_env_file() {
  mkdir -p "${HOME}/.chrysalis"
  cat >"${ENV_FILE}" <<EOF
# Generated by scripts/gce-install-native-oracle-deps.sh — source before hub native oracle smokes.
export CHRYSALIS_HUB_PYTHON="${VENV}/bin/python"
export GEM_HOME="${HOME}/.chrysalis/ruby-gems"
export PATH="/usr/local/go/bin:\${GEM_HOME}/bin:\${PATH}"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1
EOF
}

if [[ -f "${MARKER}" && "${CHRYSALIS_FORCE_NATIVE_ORACLE_DEPS:-}" != "1" ]]; then
  ensure_python_venv
  install_go_122
  ensure_ruby_gems
  write_env_file
  echo "[gce-install-native-oracle-deps] OK (cached ${MARKER})"
  exit 0
fi

export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -qq

sudo apt-get install -y \
  ca-certificates \
  curl \
  default-jdk-headless \
  ruby \
  ruby-dev \
  build-essential \
  python3-venv \
  python3-full \
  php-cli \
  php-xml \
  unzip \
  || true

install_go_122

if ! command -v dotnet >/dev/null 2>&1; then
  if [[ -f /etc/os-release ]]; then
    # shellcheck source=/dev/null
    . /etc/os-release
    if [[ "${ID:-}" == "debian" && -n "${VERSION_ID:-}" ]]; then
      tmpdeb="/tmp/packages-microsoft-prod.deb"
      if curl -fsSL "https://packages.microsoft.com/config/debian/${VERSION_ID}/packages-microsoft-prod.deb" -o "${tmpdeb}"; then
        sudo dpkg -i "${tmpdeb}" || true
        sudo apt-get update -qq
        sudo apt-get install -y dotnet-sdk-9.0 || sudo apt-get install -y dotnet-sdk-8.0 || true
      fi
    fi
  fi
else
  if ! dotnet --list-sdks 2>/dev/null | grep -q '^9\.'; then
    sudo apt-get install -y dotnet-sdk-9.0 || true
  fi
fi

ensure_python_venv
ensure_ruby_gems
write_env_file

missing=()
command -v javac >/dev/null 2>&1 || missing+=("javac")
/usr/local/go/bin/go version >/dev/null 2>&1 || missing+=("go-1.22")
command -v ruby >/dev/null 2>&1 || missing+=("ruby")
dotnet --list-sdks 2>/dev/null | grep -q '^9\.' || missing+=("dotnet-sdk-9")
"${VENV}/bin/python" -c "import flask" 2>/dev/null || missing+=("flask-venv")
ruby -e "require 'sinatra/base'" 2>/dev/null || missing+=("sinatra-gem")

if [[ ${#missing[@]} -gt 0 ]]; then
  echo "[gce-install-native-oracle-deps] WARN: missing ${missing[*]}" >&2
  exit 1
fi

date -Is >"${MARKER}"
echo "[gce-install-native-oracle-deps] OK — CHRYSALIS_HUB_PYTHON=${VENV}/bin/python"
